version: '3.7'
 
services:
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   - PMA_HOST=mysql
  restart: always
  ports:
   - 9090:80
 mysql:
  image: mysql:5.6
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
 itop:
  build: ./itop
  container_name: itop
  restart: always
  ports:
   - 8080:80
 integria_ims:
  build: ./integria_ims
  container_name: integria_ims
  restart: always
  ports:
   - 8081:80

   

