version: '3.7'
 
services:
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_HOST=mysql
  restart: always
  ports:
   - 9090:80
 mysql:
  image: mysql:5.6
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD: 123456
 web:
  build: .
  container_name: web
  environment:
   - INTEGRIA_DB_HOST: mysql
   - INTEGRIA_DB_USER: root
   - INTEGRIA_DB_PASSWORD: 123456
   - INTEGRIA_DB_NAME: integria
  ports:
   - 8080:80
volumes:
 db_data:
